In [1]:
# Cargamos librerías y configuramos opciones óptimas para el proyecto
import pandas as pd
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 1000)

**Ruta de entrada**

In [2]:
# Ruta de entrada
Ruta_data_preprocesada = '../../Data/data_preprocesada'
Ruta_data_procesada = '../../Data/data_procesada'
Ruta_data_procesada_full = r'C:\Users\jalvarez\OneDrive\Estudios\Programacion\Soy Henry Datos e IA\Dataft21\PG\Data\data_procesada' # Donde estan todos los datasets no importa su peso por la limitante de GitHub. Si solo se tiene una única carpera 'Ruta_data_procesada' donde está todo pues colocar en ambas variables la misma ruta

**Ruta de salida**

In [3]:
Ruta_data_preprocesada = '../../Data/data_preprocesada'
Ruta_data_procesada = '../../Data/data_procesada'

## Checking

In [4]:
table_checkin = pd.read_parquet(os.path.join(Ruta_data_procesada, "Dataset_Checkin.parquet"))
table_checkin

                     business_id      hour       date  year  month
0         ---kPU91CF4Lq2-WlRu9Lw  21:10:56 2020-03-13  2020      3
1         ---kPU91CF4Lq2-WlRu9Lw  22:18:06 2020-06-02  2020      6
2         ---kPU91CF4Lq2-WlRu9Lw  22:42:27 2020-07-24  2020      7
3         ---kPU91CF4Lq2-WlRu9Lw  21:36:13 2020-10-24  2020     10
4         ---kPU91CF4Lq2-WlRu9Lw  21:23:33 2020-12-09  2020     12
...                          ...       ...        ...   ...    ...
13356870  zzu6_r3DxBJuXcjnOYVdTw  00:52:49 2013-12-11  2013     12
13356871  zzu6_r3DxBJuXcjnOYVdTw  00:58:14 2013-12-13  2013     12
13356872  zzw66H6hVjXQEt0Js3Mo4A  23:33:26 2016-12-03  2016     12
13356873  zzw66H6hVjXQEt0Js3Mo4A  19:08:45 2018-12-02  2018     12
13356874  zzyx5x0Z7xXWWvWnZFuxlQ  17:51:53 2015-01-06  2015      1

[13356875 rows x 5 columns]

In [5]:
table_checkin = table_checkin.drop_duplicates(subset=['business_id', 'hour', 'date'])

In [6]:
table_checkin.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13353332 entries, 0 to 13356874
Data columns (total 5 columns):
 #   Column       Dtype
---  ------       -----
 0   business_id  object
 1   hour         object
 2   date         datetime64[ns]
 3   year         int32
 4   month        int32
dtypes: datetime64[ns](1), int32(2), object(2)
memory usage: 509.4+ MB

In [7]:
# Exportamos
table_checkin.to_parquet(os.path.join(Ruta_data_procesada, "Dataset_Checkin.parquet"))

## Tip

In [8]:
table_tip = pd.read_parquet(os.path.join(Ruta_data_procesada, "Dataset_Tip.parquet"))
table_tip.head(2)

,id_user,id_business,text,date,compliment_count
0,66477,140105,They have lots of good deserts and tasty cuban sandwiches,2013-02-05 18:35:10,0
1,49975,865,It's open even when you think it isn't,2013-08-18 00:56:08,0

In [9]:
valores_nulos = table_tip[table_tip['text'].isnull()]
valores_nulos

Empty DataFrame
Columns: [id_user, id_business, text, date, compliment_count]
Index: []

In [10]:
duplicates = table_tip.duplicated(subset=['id_user', 'id_business', 'text', 'date'], keep=False)
# Filtrar el DataFrame original para mostrar solo las filas duplicadas
duplicated_rows = table_tip[duplicates]
duplicated_rows

,id_user,id_business,text,date,compliment_count
9955,7914,57121,LM,2011-11-22 12:48:02,0
14789,961,1652,Late dinner w @steinerrecliner,2011-01-31 01:07:40,0
23530,14379,139469,Com chien and mi are delish!,2011-07-23 17:22:58,0
26964,14379,139469,Com chien and mi are delish!,2011-07-23 17:22:58,0
31925,106029,25537,"Love it. Very special, unique and delizioso!",2017-04-01 23:52:40,0
...,...,...,...,...,...
358126,868497,107606,This place is really nice,2017-09-05 03:36:35,0
369607,1073923,100522,"Excellent condition, food, and staff.",2016-10-08 21:45:48,0
371384,1073923,100522,"Excellent condition, food, and staff.",2016-10-08 21:45:48,0
377725,1036767,47648,"Great place, great baked goods!",2019-06-08 17:06:50,0
379132,1036767,47648,"Great place, great baked goods!",2019-06-08 17:06:50,0

In [11]:
table_tip = table_tip.drop_duplicates(subset=['id_user', 'id_business', 'text', 'date'])

In [12]:
table_tip.info()

<class 'pandas.core.frame.DataFrame'>
Index: 433330 entries, 0 to 433367
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_user           433330 non-null  int64
 1   id_business       433330 non-null  int64
 2   text              433330 non-null  object
 3   date              433330 non-null  object
 4   compliment_count  433330 non-null  int64
dtypes: int64(3), object(2)
memory usage: 19.8+ MB

In [13]:
table_tip.to_parquet(os.path.join(Ruta_data_procesada, "Dataset_Tip.parquet"))

## Businnes

In [14]:
table_business = pd.read_parquet(os.path.join(Ruta_data_procesada, "Dataset_Business.parquet"))
table_business.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists",None
1,3,St Honore Pastries,935 Race St,Philadelphia,Pennsylvania,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': 'False', 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '1', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessi...","Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0', 'Thursday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0'}"

In [15]:
null_indices_hora = table_business['hours'].isnull()
null_indices_hora

0         True
1        False
2        False
3        False
4        False
         ...
72510    False
72511    False
72512    False
72513    False
72514    False
Name: hours, Length: 72515, dtype: bool

In [16]:
random_row = table_business.sample()
random_hours_value = random_row['hours'].values[0]
random_hours_value

{'Friday': '15:0-4:0',
 'Monday': '15:0-4:0',
 'Saturday': '15:0-4:0',
 'Sunday': '15:0-4:0',
 'Thursday': '15:0-4:0',
 'Tuesday': '15:0-4:0',
 'Wednesday': '15:0-4:0'}

In [17]:
horario_general = {'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}

In [18]:
# Colocamos un horario genperico 'horario_general' a los establecimientos sin horarios 'hours'
table_business.loc[null_indices_hora, 'hours'] = table_business.loc[null_indices_hora].apply(lambda row: horario_general, axis=1)

In [19]:

null_indices = table_business['hours'].isnull()
null_indices

0        False
1        False
2        False
3        False
4        False
         ...
72510    False
72511    False
72512    False
72513    False
72514    False
Name: hours, Length: 72515, dtype: bool

In [20]:
table_business['hours'].isnull().sum()

0

Se había ideado una función para obtener el estado desde latitud/longitud, pero se ha preferido obtenerlo desde código postal 'postal_code'. Entonces lo comento como archivo/recuerdo. Atte: Jorge

In [21]:
# import geocoder

# def get_postal_code(latitude, longitude):
#     location = geocoder.osm([latitude, longitude], method='reverse')
#     return location.postal

In [22]:
#reemplazo los valores nulos en la tabla
#table_business.loc[null_indices, 'postal_code'] = table_business.loc[null_indices].apply(lambda row: get_postal_code(row['latitude'], row['longitude']), axis=1)

In [23]:
#valores_nulos = table_business[table_business['postal_code'].isnull()]
#valores_nulos
#este valor nulo me manda al medio del mar por eso no tiene postal code. Considerar si lo borramos o no

In [24]:
#faltante = get_postal_code(32.105261,110.942001)
#print(faltante)

In [25]:
#table_business['postal_code'] = table_business['postal_code'].astype(float)
#REVISAR MAÑANA

In [26]:
duplicates_mask = table_business['address'].duplicated(keep=False)
duplicated_addresses = table_business[duplicates_mask]
duplicated_addresses.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
5,11,Vietnamese Food Truck,,Tampa Bay,Florida,33602,27.955269,-82.456320,4.0,10,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': ''none'', 'Ambience': '{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': False, 'upscale': False, 'classy': False, 'casual': False}', 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': False, 'dinner': False, 'brunch': False, 'breakfast': False}', 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'None', 'RestaurantsAttire': None, 'Restauran...","Vietnamese, Food, Restaurants, Food Trucks","{'Friday': '11:0-14:0', 'Monday': '11:0-14:0', 'Saturday': '5:0-10:0', 'Sunday': '15:0-18:0', 'Thursday': '11:0-14:0', 'Tuesday': '11:0-14:0', 'Wednesday': '11:0-14:0'}"
7,14,Zio's Italian Market,2575 E Bay Dr,Largo,Florida,33771,27.916116,-82.760461,4.5,100,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': '{'romantic': False, 'intimate': False, 'touristy': False, 'hipster': False, 'divey': False, 'classy': False, 'trendy': False, 'upscale': False, 'casual': True}', 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': 'False', 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': 'True', 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': False, 'breakfast': False}', 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': 'True', 'Music': None, 'NoiseLevel': 'u'average'', 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttir...","Food, Delis, Italian, Bakeries, Restaurants","{'Friday': '10:0-20:0', 'Monday': '10:0-18:0', 'Saturday': '10:0-20:0', 'Sunday': None, 'Thursday': '10:0-20:0', 'Tuesday': '10:0-20:0', 'Wednesday': '10:0-20:0'}"

In [27]:
table_business.drop_duplicates(subset=['latitude', 'longitude', 'postal_code'], inplace=True)
table_business.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}"
1,3,St Honore Pastries,935 Race St,Philadelphia,Pennsylvania,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': 'False', 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '1', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessi...","Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0', 'Thursday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0'}"

In [28]:
table_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65827 entries, 0 to 72514
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_business   65827 non-null  int64
 1   name          65827 non-null  object
 2   address       65827 non-null  object
 3   city          65827 non-null  object
 4   state         65827 non-null  object
 5   postal_code   65827 non-null  int64
 6   latitude      65827 non-null  float64
 7   longitude     65827 non-null  float64
 8   stars         65827 non-null  float64
 9   review_count  65827 non-null  int64
 10  is_open       65827 non-null  int64
 11  attributes    59662 non-null  object
 12  categories    65827 non-null  object
 13  hours         65827 non-null  object
dtypes: float64(3), int64(4), object(7)
memory usage: 7.5+ MB

In [29]:
duplicates_mask = table_business.duplicated(subset=['latitude', 'longitude', 'postal_code'], keep=False)
num_duplicates = duplicates_mask.sum()
num_duplicates

0

Código para desglosar cada establecimiento por cata 'categories', pero no estoy seguro si se utilizará despues y aumenta enormemente el dataset así que lo comento por ahora. Atte: Jorge.

In [30]:
# rows = []

# # Iterar sobre cada fila del DataFrame original
# for index, row in table_business.iterrows():
#     # Obtener las categorías de la fila actual
#     categories = row['categories']
    
#     # Si hay categorías
#     if categories:
#         # Dividir las categorías y eliminar espacios en blanco
#         categories_list = [category.strip() for category in categories.split(',')]
        
#         # Iterar sobre cada categoría y duplicar la fila actual
#         for category in categories_list:
#             # Crear una copia de la fila actual
#             new_row = row.copy()
#             # Asignar la categoría actual a la fila copiada
#             new_row['categories'] = category
#             # Agregar la fila copiada a la lista
#             rows.append(new_row)

# # Crear un nuevo DataFrame con las filas duplicadas
# table_business = pd.DataFrame(rows)

In [31]:
# Creamos nueva columna con primer 'categories' de cada establecimiento
table_business['first_category'] = table_business['categories'].str.split(',').str[0]
table_business.head(5)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,first_category
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors
1,3,St Honore Pastries,935 Race St,Philadelphia,Pennsylvania,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': 'False', 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '1', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessi...","Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0', 'Thursday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0'}",Restaurants
2,4,Perkiomen Valley Brewery,101 Walnut St,Green Lane,Pennsylvania,18054,40.338183,-75.471659,4.5,13,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': None, 'street': None, 'validated': None, 'lot': True, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': 'False', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': 'True', 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessible': 'True', ...","Brewpubs, Breweries, Food","{'Friday': '12:0-22:0', 'Monday': None, 'Saturday': '12:0-22:0', 'Sunday': '12:0-18:0', 'Thursday': '16:0-22:0', 'Tuesday': None, 'Wednesday': '14:0-22:0'}",Brewpubs
3,7,Temple Beth-El,400 Pasadena Ave S,St. Petersburg,Florida,33707,27.766590,-82.732983,3.5,5,1,None,"Synagogues, Religious Organizations","{'Friday': '9:0-17:0', 'Monday': '9:0-17:0', 'Saturday': None, 'Sunday': None, 'Thursday': '9:0-17:0', 'Tuesday': '9:0-17:0', 'Wednesday': '9:0-17:0'}",Synagogues
4,10,Marshalls,21705 Village Lakes Sc Dr,Land O' Lakes,Florida,34639,28.190459,-82.457380,3.5,6,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '2', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi'...","Department Stores, Shopping, Fashion","{'Friday': '9:30-21:30', 'Monday': '9:30-21:30', 'Saturday': '9:30-21:30', 'Sunday': '10:0-20:0', 'Thursday': '9:30-21:30', 'Tuesday': '9:30-21:30', 'Wednesday': '9:30-21:30'}",Department Stores

**Uniremos la tabla 'business' con los otros dataset para tener un único dataframe completo**

In [32]:
# Cargamos los dataframes creados en la etapa anterior de ETL
BusinessDetalleAtributos = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessDetalleAtributos.csv"))
BusinessAtributos = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessAtributos.csv"))
BusinessDetalleCategorias = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessDetalleCategorias.csv"))
BusinessCategorias = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessCategorias.csv"))
BusinessDetallesHora = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessDetallesHora.csv"))
BusinessHoras = pd.read_csv(os.path.join(Ruta_data_preprocesada, "BusinessHoras.csv"))
Dataset_Tip = pd.read_parquet(os.path.join(Ruta_data_procesada, "Dataset_Tip.parquet"))

In [33]:
Dataset_Business = table_business.copy()
Dataset_Business.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,first_category
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors
1,3,St Honore Pastries,935 Race St,Philadelphia,Pennsylvania,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': 'False', 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '1', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessi...","Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0', 'Thursday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0'}",Restaurants

In [34]:
BusinessDetalleAtributos.head(2)

   id_business  IdAtributos
0            0            0
1            1            1

In [35]:
BusinessAtributos.head(2)

           Descripcion  IdAtributos
0    ByAppointmentOnly            0
1  RestaurantsDelivery            1

In [36]:
BusinessDetalleCategorias.head(2)

   id_business  IdCategoria
0            0            0
1            0            1

In [37]:
BusinessCategorias.head(2)

                     Descripcion  IdCategoria
0                        Doctors            0
1   Traditional Chinese Medicine            1

In [38]:
BusinessDetallesHora.head(2)

   id_business   hours
0            0     NaN
1            3  Monday

In [39]:
BusinessHoras.head(2)

,id_business,hours
0,0,NaN
1,1,"{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0', 'Thursday': '7:0-20:0', 'Friday': '7:0-21:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0'}"

In [40]:
Dataset_Tip.head(2)

,id_user,id_business,text,date,compliment_count
0,66477,140105,They have lots of good deserts and tasty cuban sandwiches,2013-02-05 18:35:10,0
1,49975,865,It's open even when you think it isn't,2013-08-18 00:56:08,0

In [41]:
# Unimos los dataframes (Demora 1-2 min aprox.)
Dataset_Business_extendido = Dataset_Business.merge(BusinessDetalleAtributos, on='id_business', how='left').merge(BusinessAtributos, on='IdAtributos', how='left').merge(BusinessDetalleCategorias, on='id_business', how='left').merge(BusinessCategorias, on='IdCategoria', how='left').merge(BusinessDetallesHora, on='id_business', how='left').merge(BusinessHoras, on='id_business', how='left').merge(Dataset_Tip, on='id_business', how='left')
Dataset_Business_extendido.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours_x,first_category,IdAtributos,Descripcion_x,IdCategoria,Descripcion_y,hours_y,hours,id_user,text,date,compliment_count
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,0.0,ByAppointmentOnly,0.0,Doctors,NaN,NaN,NaN,NaN,NaN,NaN
1,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,0.0,ByAppointmentOnly,1.0,Traditional Chinese Medicine,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Renombramos algunas columnas para mayor comprensión
Dataset_Business_extendido.rename(columns={"Descripcion_x": "Descripcion_BusinessAtributos",
                            "Descripcion_y": "Descripcion_BusinessCategorias",
                            "hours_x": "hours_Dataset_Business",
                            "hours_y": "hours_BusinessDetallesHora",
                            "hours": "BusinessHoras"}, inplace=True)
Dataset_Business_extendido.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours_Dataset_Business,first_category,IdAtributos,Descripcion_BusinessAtributos,IdCategoria,Descripcion_BusinessCategorias,hours_BusinessDetallesHora,BusinessHoras,id_user,text,date,compliment_count
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,0.0,ByAppointmentOnly,0.0,Doctors,NaN,NaN,NaN,NaN,NaN,NaN
1,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,0.0,ByAppointmentOnly,1.0,Traditional Chinese Medicine,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Borramos las columnas ya no necesarias
Dataset_Business_extendido.drop(columns=["address", "is_open", "attributes", "IdAtributos", "IdCategoria", "hours_BusinessDetallesHora", "BusinessHoras", "id_user", "text"], axis=1, inplace=True)
Dataset_Business_extendido.head(2)

,id_business,name,city,state,postal_code,latitude,longitude,stars,review_count,categories,hours_Dataset_Business,first_category,Descripcion_BusinessAtributos,Descripcion_BusinessCategorias,date,compliment_count
0,0,"Abby Rappoport, LAC, CMQ",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,"Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,ByAppointmentOnly,Doctors,NaN,NaN
1,0,"Abby Rappoport, LAC, CMQ",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,"Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists","{'Friday': '9:0-20:0', 'Monday': '9:0-20:0', 'Saturday': '8:30-15:30', 'Sunday': None, 'Thursday': '9:0-20:0', 'Tuesday': '9:0-20:0', 'Wednesday': '9:0-20:0'}",Doctors,ByAppointmentOnly,Traditional Chinese Medicine,NaN,NaN

In [44]:
# Exportamos a parquet (Demora 4 min aprox.)
Dataset_Business_extendido.to_parquet(os.path.join(Ruta_data_procesada, "Dataset_Business_extendido.parquet"))

## reviews Yelp

In [58]:
table_reviews = pd.read_parquet(os.path.join(Ruta_data_procesada_full, "Dataset_Review.parquet"))
table_reviews.head(3)

,user_id,stars,useful,funny,cool,text,date,id_review,id_user,id_business
0,mh_-eMZ6K5RLWhZyISBhwA,3.0,0,0,0,"If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience. \n\nThe food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.",2018-07-07 22:09:11,0,124234,1867
1,OyoGAe7OKpv6SyGZT5g77Q,5.0,1,0,1,"I've taken a lot of spin classes over the years, and nothing compares to the classes at Body Cycle. From the nice, clean space and amazing bikes, to the welcoming and motivating instructors, every class is a top notch work out.\n\nFor anyone who struggles to fit workouts in, the online scheduling system makes it easy to plan ahead (and there's no need to line up way in advanced like many gyms make you do).\n\nThere is no way I can write this review without giving Russell, the owner of Body Cycle, a shout out. Russell's passion for fitness and cycling is so evident, as is his desire for all of his clients to succeed. He is always dropping in to classes to check in/provide encouragement, and is open to ideas and recommendations from anyone. Russell always wears a smile on his face, even when he's kicking your butt in class!",2012-01-03 15:28:18,1,51327,12886
2,_7bHUi9Uuf5__HHc_Q8guQ,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",2015-01-04 00:01:03,3,164430,6316

In [59]:
# Separar los elementos de la columna "date" en cuatro columnas
date_split = table_reviews['date'].str.split(' ', expand=True)

# Asignar nombres a las nuevas columnas
date_split.columns = ['fecha', 'hora']

# Dividir la columna "fecha" en columnas separadas para año, mes y día
date_split[['anho', 'mes', 'dia']] = date_split['fecha'].str.split('-', expand=True)

# Unir las nuevas columnas con el DataFrame original
table_reviews = table_reviews.join(date_split[['anho', 'mes', 'dia', 'hora']])

# Eliminar la columna "date"
table_reviews.drop(columns=['date'], inplace=True)

In [60]:
table_reviews.head(2)

,user_id,stars,useful,funny,cool,text,id_review,id_user,id_business,anho,mes,dia,hora
0,mh_-eMZ6K5RLWhZyISBhwA,3.0,0,0,0,"If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience. \n\nThe food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.",0,124234,1867,2018,07,07,22:09:11
1,OyoGAe7OKpv6SyGZT5g77Q,5.0,1,0,1,"I've taken a lot of spin classes over the years, and nothing compares to the classes at Body Cycle. From the nice, clean space and amazing bikes, to the welcoming and motivating instructors, every class is a top notch work out.\n\nFor anyone who struggles to fit workouts in, the online scheduling system makes it easy to plan ahead (and there's no need to line up way in advanced like many gyms make you do).\n\nThere is no way I can write this review without giving Russell, the owner of Body Cycle, a shout out. Russell's passion for fitness and cycling is so evident, as is his desire for all of his clients to succeed. He is always dropping in to classes to check in/provide encouragement, and is open to ideas and recommendations from anyone. Russell always wears a smile on his face, even when he's kicking your butt in class!",1,51327,12886,2012,01,03,15:28:18

In [61]:
# Identificar filas duplicadas basadas en múltiples columnas
#duplicates = table_reviews.duplicated(subset=['user_id', 'text', 'id_user', 'id_business', 'anho', 'mes', 'dia'], keep=False)
duplicates = table_reviews.duplicated(subset=['user_id', 'id_business', 'anho', 'mes', 'dia'], keep=False)
# Filtrar el DataFrame original para mostrar solo las filas duplicadas
duplicated_rows = table_reviews[duplicates]
duplicated_rows.head(2)

,user_id,stars,useful,funny,cool,text,id_review,id_user,id_business,anho,mes,dia,hora
1750,2anfbsmeoqeMYCiNwUow9Q,5.0,3,0,2,The staff at VIP and Concierge Services is A+. They took care of all our needs immediately and with grace and charm. Big thanks to Kevin Brantner for arranging a wonderful weekend for us.,3427,105222,9506,2013,06,24,23:03:56
1764,WvVuX_7Ut_AV1hAZ5O-yFA,2.0,1,0,0,"It is sad but seemingly true that this place has survived for years on the overflow traffic from some of the other places at John's Pass. Tired of the wait at Bubba Gump? Not in the mood for pizza from Delosa's? Just realized that you paid for parking and that Walt'z has closed for the day - plus your feet hurt from a day at the beach ... stop for a while at Sculley's and take what they serve you. If you can find a server, that is. \n\nActually, the service isn't that bad ... the problem is with the layout of the place. The shops here want to have an eclectic air, as though they were built from driftwood and shipping crates held together with sail cloth and rope. This is fine in fantasy, but in reality does not make it easy for the wait staff to get around easily of remain within eye sight of their tables. \n\nThe food is passable, but unexceptional. Being a stone throw away from Gulf of Mexico means that a restaurant can lean towards basic tourist fare (they likely won't know how ...",3454,46563,7907,2013,06,24,18:08:09

In [62]:
table_reviews = table_reviews.drop_duplicates(subset=['user_id', 'id_business', 'anho', 'mes', 'dia'])
table_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3514973 entries, 0 to 3515683
Data columns (total 13 columns):
 #   Column       Dtype
---  ------       -----
 0   user_id      object
 1   stars        float64
 2   useful       int64
 3   funny        int64
 4   cool         int64
 5   text         object
 6   id_review    int64
 7   id_user      int64
 8   id_business  int64
 9   anho         object
 10  mes          object
 11  dia          object
 12  hora         object
dtypes: float64(1), int64(6), object(6)
memory usage: 375.4+ MB

In [63]:
table_reviews.isnull().sum()

user_id        0
stars          0
useful         0
funny          0
cool           0
text           0
id_review      0
id_user        0
id_business    0
anho           0
mes            0
dia            0
hora           0
dtype: int64

In [64]:
# Cargamos los dataframes creados en la etapa anterior de ETL
Dataset_Business = pd.read_parquet(os.path.join(Ruta_data_procesada, "Dataset_Business.parquet"))
UsuarioYelp = pd.read_csv(os.path.join(Ruta_data_preprocesada, "UsuarioYelp.csv"))

In [65]:
Dataset_Review = table_reviews.copy()

In [66]:
Dataset_Business.head(2)

,id_business,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,California,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': None, 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': None, 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': None, 'BusinessParking': None, 'ByAppointmentOnly': 'True', 'Caters': None, 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': None, 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': None, 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': None, 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': None, 'Smoking': None, 'WheelchairAccessible': None, 'WiFi': None}","Doctors, Traditional Chinese Medicine, Naturopathic/Holistic, Acupuncture, Health & Medical, Nutritionists",None
1,3,St Honore Pastries,935 Race St,Philadelphia,Pennsylvania,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': 'u'none'', 'Ambience': None, 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'True', 'BusinessAcceptsBitcoin': None, 'BusinessAcceptsCreditCards': 'False', 'BusinessParking': '{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}', 'ByAppointmentOnly': 'False', 'Caters': 'True', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': None, 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': None, 'GoodForMeal': None, 'HairSpecializesIn': None, 'HappyHour': None, 'HasTV': None, 'Music': None, 'NoiseLevel': None, 'Open24Hours': None, 'OutdoorSeating': 'False', 'RestaurantsAttire': None, 'RestaurantsCounterService': None, 'RestaurantsDelivery': 'False', 'RestaurantsGoodForGroups': None, 'RestaurantsPriceRange2': '1', 'RestaurantsReservations': None, 'RestaurantsTableService': None, 'RestaurantsTakeOut': 'True', 'Smoking': None, 'WheelchairAccessi...","Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', 'Saturday': '7:0-21:0', 'Sunday': '7:0-21:0', 'Thursday': '7:0-20:0', 'Tuesday': '7:0-20:0', 'Wednesday': '7:0-20:0'}"

In [67]:
UsuarioYelp.head(2)

   id_user                 yelp_id
0        0  qVc8ODYU5SZjKXVBgXdI7w
1        1  j14WgRoU_-2ZE1aw1dXrJg

In [68]:
# Unimos los dataframes
Dataset_Review_extendido = Dataset_Review.merge(Dataset_Business, on='id_business', how='left').merge(UsuarioYelp, on='id_user', how='left')
Dataset_Review_extendido.head(1)

,user_id,stars_x,useful,funny,cool,text,id_review,id_user,id_business,anho,mes,dia,hora,name,address,city,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours,yelp_id
0,mh_-eMZ6K5RLWhZyISBhwA,3.0,0,0,0,"If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience. \n\nThe food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.",0,124234,1867,2018,07,07,22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,Pennsylvania,19454,40.210196,-75.223639,3.0,169,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': ''none'', 'Ambience': '{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': False, 'upscale': False, 'classy': False, 'casual': True}', 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'False', 'BusinessAcceptsBitcoin': 'False', 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': 'False', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': 'False', 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': 'True', 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}', 'HairSpecializesIn': None, 'HappyHour': 'False', 'HasTV': 'False', 'Music': None, 'NoiseLevel': 'u'average'', 'Open24Hours': None, 'OutdoorSeating': 'True', 'Restaurants...","Restaurants, Breakfast & Brunch, Food, Juice Bars & Smoothies, American (New), Coffee & Tea, Sandwiches","{'Friday': '7:30-15:0', 'Monday': '7:30-15:0', 'Saturday': '7:30-15:0', 'Sunday': '7:30-15:0', 'Thursday': '7:30-15:0', 'Tuesday': '7:30-15:0', 'Wednesday': '7:30-15:0'}",mh_-eMZ6K5RLWhZyISBhwA

In [69]:
# Renombramos algunas columnas para mayor comprensión
Dataset_Review_extendido.rename(columns={"stars_x": "stars_Dataset_Review",
                            "stars_y": "stars_Dataset_Business"}, inplace=True)
Dataset_Review_extendido.head(1)

,user_id,stars_Dataset_Review,useful,funny,cool,text,id_review,id_user,id_business,anho,mes,dia,hora,name,address,city,state,postal_code,latitude,longitude,stars_Dataset_Business,review_count,is_open,attributes,categories,hours,yelp_id
0,mh_-eMZ6K5RLWhZyISBhwA,3.0,0,0,0,"If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience. \n\nThe food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.",0,124234,1867,2018,07,07,22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,Pennsylvania,19454,40.210196,-75.223639,3.0,169,1,"{'AcceptsInsurance': None, 'AgesAllowed': None, 'Alcohol': ''none'', 'Ambience': '{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': False, 'upscale': False, 'classy': False, 'casual': True}', 'BYOB': None, 'BYOBCorkage': None, 'BestNights': None, 'BikeParking': 'False', 'BusinessAcceptsBitcoin': 'False', 'BusinessAcceptsCreditCards': 'True', 'BusinessParking': '{'garage': False, 'street': False, 'validated': False, 'lot': True, 'valet': False}', 'ByAppointmentOnly': None, 'Caters': 'False', 'CoatCheck': None, 'Corkage': None, 'DietaryRestrictions': None, 'DogsAllowed': 'False', 'DriveThru': None, 'GoodForDancing': None, 'GoodForKids': 'True', 'GoodForMeal': '{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': False, 'brunch': True, 'breakfast': True}', 'HairSpecializesIn': None, 'HappyHour': 'False', 'HasTV': 'False', 'Music': None, 'NoiseLevel': 'u'average'', 'Open24Hours': None, 'OutdoorSeating': 'True', 'Restaurants...","Restaurants, Breakfast & Brunch, Food, Juice Bars & Smoothies, American (New), Coffee & Tea, Sandwiches","{'Friday': '7:30-15:0', 'Monday': '7:30-15:0', 'Saturday': '7:30-15:0', 'Sunday': '7:30-15:0', 'Thursday': '7:30-15:0', 'Tuesday': '7:30-15:0', 'Wednesday': '7:30-15:0'}",mh_-eMZ6K5RLWhZyISBhwA

In [70]:
# Exportamos a parquet
Dataset_Review_extendido.to_parquet(os.path.join(Ruta_data_procesada, "Dataset_Review_extendido.parquet"))